### ISSUE TITLE
resize instance faild

### ISSUE THREAD

**Issue by pootow** [jiasir/playback#13]
I'm using os-beta, see error bellow

Error: Failed to launch instance "nn": Please try again later [Error: Unexpected error while running command. Command: ssh 10.32.151.16 mkdir -p /var/lib/nova/instances/e8f1f147-9172-4125-9584-c083a23c3b4d Exit code: 255 Stdout: u'' Stderr: u'Host key verification failed.\r\n'].

**Comment by jiasir** [comment]
Thanks for your reporting. I fixed it, please try it again.
