### ISSUE TITLE
Live Migration failure

### ISSUE THREAD

**Issue by jiasir** [jiasir/playback#16]
Using ceph as cinder and glance backend. Executing Live Migration form horizon or command-line, the nova err:
```
Live Migration failure: internal error: unable to execute QEMU command 'migrate': Migration disabled: failed to allocate shared memory
```
The libvirt err:
```
error : qemuProcessPrepareChardevDevice:2849 : Unable to pre-create chardev file '/var/lib/nova/instances/ecbaa245-78ea-49ef-8edc-99704c757618/console.log': No such file or directory
error : qemuMigrationPrepareDirect:3844 : invalid argument: missing scheme in migration URI: list
warning : AppArmorSetFDLabel:982 : could not find path for descriptor /proc/self/fd/30, skipping
error : qemuMonitorJSONCheckError:382 : internal error: unable to execute QEMU command 'migrate': Migration disabled: failed to allocate shared memory
error : virNetClientProgramDispatchError:177 : internal error: info migration reply was missing return status
qemuMonitorJSONCheckError:382 : internal error: unable to execute QEMU command 'migrate': Migration disabled: failed to allocate shared memory
virNetClientProgramDispatchError:177 : internal error: info migration reply was missing return status
```

**Comment by jiasir** [comment]
Fixed on xenial.

**Comment by swat30** [comment]
@jiasir we're seeing the same thing happening occasionally on our Trusty install base. Do you know which packages in particular were causing the issue? We're running upstream QEMU 2.5, so I doubt that's the issue, however we're running libvirt and kernel from Ubuntu.

**Comment by jiasir** [comment]
@swat30 On trusty, the QEMU cannot execute live migrate when using the ceph backend, the live migration will create a `console.log` on target server. But the target server could not created it. upgrade `qemu-kvm` to 2.5 and `libvirt-bin` to 1.3.1 will resolve the issue. Or upgrade to xenial release.
